// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// computeR0bar
double computeR0bar(NumericVector vec, int numPerm);
RcppExport SEXP sharpeRratio_computeR0bar(SEXP vecSEXP, SEXP numPermSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type numPerm(numPermSEXP);
    __result = Rcpp::wrap(computeR0bar(vec, numPerm));
    return __result;
END_RCPP
}
