# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeR0bar <- function(vec, numPerm = 100L) {
    .Call('sharpeRratio_computeR0bar', PACKAGE = 'sharpeRratio', vec, numPerm)
}

